### ISSUE TITLE
Close toggle

### ISSUE THREAD

**Issue by adomrockie** [zesik/react-splitter-layout#11]
This is great but I do not get why there are no props to close a pane dynamically.

Unless I am missing something. I want to hide a pane when I set a prop to show or hide it.

**Comment by zesik** [comment]
Hi,

Now it does not have any props to set visibility of child panes.

Meanwhile, you can always choose not to render one child pane, like here:
https://github.com/zesik/react-splitter-layout/blob/3.0.0/example/javascripts/components/TogglableSidebarLayout.jsx

**Comment by zesik** [comment]
Closing due to no update for a long time.
