### ISSUE TITLE
do you need this absolute positioning?

### ISSUE THREAD

**Issue by ruifortes** [zesik/react-splitter-layout#13]
https://github.com/zesik/react-splitter-layout/blob/6807401c7cc95937fa8e6d14e10addaf21937a3e/src/stylesheets/index.css#L2

**Comment by ruifortes** [comment]
I guess one should be able to provide appropriate container...nevermind

**Comment by polyakoff** [comment]
@ruifortes 
Did you figure out how to provide appropriate container?
I got a problem after using this component: the redundant vertical scrollbar appears on the page
![image](https://user-images.githubusercontent.com/5703395/40535314-63fa41aa-6011-11e8-9ee9-3f61e4d2293e.png)
I assume it is because of this absolute positioning, though I am not sure.
Would like to try providing teh container.

**Comment by mnieber** [comment]
I also believe the absolute position is a problem. I'm using this bit of layout in my React component to create a 20/80 split between 2 components (using tailwindcss):

      <div className="flex flex-row">
        <div className="w-1/5">{moveList_withHorizontalPadding}</div>
        <div className="w-4/5">{moveDiv_withHorizontalPadding}</div>
      </div>

If I instead use the splitter layout for the splitting, then a horizontal scroll-bar appears at the bottom of the browser window:

        <SplitterLayout percentage secondaryInitialSize={75}>
            {moveList_withHorizontalPadding}
            {moveDiv_withHorizontalPadding}
        </SplitterLayout>

This horizontal scroll-bar *disappears* if I remove the horizontal padding in `moveList_withHorizontalPadding` and `moveDiv_withHorizontalPadding`.

So I concluded that using the splitter layout has an unwanted side-effect: adding horizontal padding results in a horizontal scrollbar. And I suspect this has something to do with the absolute positioning. If the splitter would use flex-box, I suspect this problem would not happen.

@zesik Can you reopen this issue?

**Comment by zesik** [comment]
@mnieber `absolute` is only used for the container. Can you give me some examples/screenshots what this problem is like?

**Comment by mnieber** [comment]
@zesik I gave an example, didn't I? :-)

**Comment by zesik** [comment]
@mnieber If possible, can you provide containers of the component? It is easier to track down if we know what styles containers have.

**Comment by mnieber** [comment]
Sorry, I stopped using the splitter for the time being (I found that a static splitter is often good enough). If I really need it in some project then I can create a working code example.

**Comment by zesik** [comment]
OK. If anyone finds similar issue, leave a message here so I can check.

**Comment by jimfum** [comment]
I'd like to reopen the issue. Interestingly not many people talk about this so I suspect there's something I'm missing.

Simple react code:

```javascript
export default function App() {
  return (
    <>
      <div>
        Header line1
        <br />
        Header line2
      </div>
      <main>
        <SplitterLayout>
          <div>Pane 1</div>
          <div>Pane 2</div>
        </SplitterLayout>
      </main>
    </>
  );
}
```

The result gives unwanted vertical scrollbar. I only want the content with the splitter to take the remainder of the screen without adding it.

![image](https://user-images.githubusercontent.com/15967222/119518122-87fa8700-bd78-11eb-9a9b-198dde013426.png)

https://codesandbox.io/s/keen-keller-7umnt?file=/src/App.js
