### ISSUE TITLE
The library doesn't react to changes to props

### ISSUE THREAD

**Issue by julienw** [zesik/react-splitter-layout#14]
I try to conditionally use the splitter component: in some cases I don't want to display the secondary pane.

To do this, I set `secondaryInitialSize` to 0. This doesn't work if I set it to `0` and in a subsequent render set it to something else (like `25`). For a reason I don't completely get yet, it works in the opposite direction.

**Comment by zesik** [comment]
Hi, julienw

The `secondaryInitialSize` prop, as its name suggests, sets the *initial* size of secondary panel.

For what you would like to accomplish (hiding the secondary panel), you can choose not to render that component. Please see this example for more detail:
https://github.com/zesik/react-splitter-layout/blob/3.0.0/example/javascripts/components/TogglableSidebarLayout.jsx

**Comment by julienw** [comment]
That's what I did. I was just surprised about the behavior, so maybe it should be more documented.

**Comment by zesik** [comment]
Thanks for the suggestion! I'll consider including that into the document.
