### ISSUE TITLE
Disable Splitter Bar

### ISSUE THREAD

**Issue by bharamgundea77** [zesik/react-splitter-layout#18]
Hello, i just want to split the layout and disable the separator, there should be a line in between but it should not be a re sizable pane how i can do that ?

**Comment by zesik** [comment]
Hi,

For your use case, if you have no plan of supporting resizing, I'd suggest not use the splitter layout at all. A flex layout and a border should do the trick.

**Comment by zesik** [comment]
Closing due to no further response.

**Comment by chadacious** [comment]
You could override the style with something like:
.splitter-disabled.splitter-layout.splitter-layout-vertical > .layout-splitter {
    height: 1px;
    cursor: pointer;
}
and then use:
<SplitterLayout customClassName="splitter-disabled" vertical>

See Issue #26
