### ISSUE TITLE
Does this work on chrome on android? 

### ISSUE THREAD

**Issue by damiansilbergleithcunniff** [zesik/react-splitter-layout#19]
I tried this on my mobile and it doesn't look like it works.  I even blew the slider up to a really large size (100px) to make sure I was grabbing it but it doesn't appear to actually slide the panels.

Am I missing something?

**Comment by zesik** [comment]
Hi,

I didn't have plans to support Chrome on Android or other mobile browsers when creating this.
If many people want this, I'll consider add support of mobile devices.

**Comment by zesik** [comment]
Touch event PR has been merged, and it will be released in the next major version.
