### ISSUE TITLE
The library doesn't work well with mini-css-extract-plugin

### ISSUE THREAD

**Issue by julienw** [zesik/react-splitter-layout#30]
Since Webpack 4 the webpack folks recommend using [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) to extract the CSS data into its own file. But this doesn't work well with this library. I think that's because the distributed version is a compiled version. I don't know if there's an easy fix for this but you may have an idea...

**Comment by julienw** [comment]
[react-tabs](https://github.com/reactjs/react-tabs/) exposes both a JS file and a CSS file, and a user needs to import the CSS file explicitely. I believe this would fix this issue. This would be nice but would be a breaking change.

The nice side effect is that this would allow a user to _not_ use the default CSS -- in our project we had to override a lot of the default style.

**Comment by zesik** [comment]
Hi, sorry for replying late! Was having some busy months.

I'm planning to stop compiling CSS and release separated CSS file in next major release. Hopefully it can help with the problem you're facing.

**Comment by zesik** [comment]
This should be fixed in version 4. Please give it a try.

**Comment by julienw** [comment]
Thanks, we'll try and give some feedback :) In the mean time you can close this bug if you think this is fixed!
