### ISSUE TITLE
can u add primaryInitialSize?

### ISSUE THREAD

**Issue by arcifius** [zesik/react-splitter-layout#4]
It is nice to have secondaryInitialSize but I want to start with the first pane having 200px of height... A primaryInitialSize should solve :D

**Comment by zesik** [comment]
Hi arcifius,

By design, size of primary pane is flexible and cannot be set with initial size. Could you please try to use `secondaryInitialSize` and swap primary and secondary with `primaryIndex`?

**Comment by zesik** [comment]
Closing this due to no further information.
